class CreateDailyreports < ActiveRecord::Migration[6.1]
  def change
    create_table :dailyreports do |t|
      t.references :employee, index: true, foreign_key: true
      t.string "ym"
      t.date "date"
      t.string "kbn"
      t.string "kbn_reason"
      t.integer "prescribed_frh"
      t.integer "prescribed_frm"
      t.integer "prescribed_toh"
      t.integer "prescribed_tom"
      t.integer "lunch_frh"
      t.integer "lunch_frm"
      t.integer "lunch_toh"
      t.integer "lunch_tom"
      t.string "over_reason"
      t.integer "over_frh"
      t.integer "over_frm"
      t.integer "over_toh"
      t.integer "over_tom"
      t.integer "rest_frh"
      t.integer "rest_frm"
      t.integer "rest_toh"
      t.integer "rest_tom"
      t.string "late_reason"
      t.integer "late_h"
      t.integer "late_m"
      t.string "goout_reason"
      t.integer "goout_frh"
      t.integer "goout_frm"
      t.integer "goout_toh"
      t.integer "goout_tom"
      t.string "early_reason"
      t.integer "early_h"
      t.integer "early_m"
      t.integer "prescribed_h"
      t.integer "prescribed_m"
      t.integer "over_h"
      t.integer "over_m"
      t.integer "midnight_h"
      t.integer "midnight_m"
      t.integer "work_prescribed_h"
      t.integer "work_prescribed_m"
      t.integer "work_over_h"
      t.integer "work_over_m"
      t.string "status"
      t.bigint "approval_id"
      t.date "approval_date"
      t.timestamps
    end
  end
end
